sudo: false

os:
- osx
- linux

addons:
  artifacts:
    paths:
      - ./builds.tar.gz
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso

language:
  - node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16;
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start; sleep 3;
  fi

install:
  - npm install
  - npm prune

script: |
  npm run lint &&
  npm run test &&
  npm run build &&
  npm run archive-builds
